const emoji = (count) => '😀'.repeat(count);

export function buildCases() {
  return Object.freeze([
    { id: 'request.minimal', model: 'RequestMeta', valid: true,
      payload: '{"requestId":"r","traceId":"t"}' },
    { id: 'request.whitespace-preserved', model: 'RequestMeta', valid: true,
      payload: '{"requestId":" r ","traceId":" t ","locale":"  "}' },
    { id: 'request.locale-combining-two-codepoints', model: 'RequestMeta', valid: true,
      payload: '{"requestId":"r","traceId":"t","locale":"e\\u0301"}' },
    { id: 'request.locale-one-codepoint', model: 'RequestMeta', valid: false,
      payload: '{"requestId":"r","traceId":"t","locale":"😀"}' },
    { id: 'request.locale-max-codepoints', model: 'RequestMeta', valid: true,
      payload: JSON.stringify({ requestId: 'r', traceId: 't', locale: emoji(64) }) },
    { id: 'request.locale-over-codepoints', model: 'RequestMeta', valid: false,
      payload: JSON.stringify({ requestId: 'r', traceId: 't', locale: emoji(65) }) },
    { id: 'request.id-max-codepoints', model: 'RequestMeta', valid: true,
      payload: JSON.stringify({ requestId: emoji(128), traceId: 't' }) },
    { id: 'request.id-over-codepoints', model: 'RequestMeta', valid: false,
      payload: JSON.stringify({ requestId: emoji(129), traceId: 't' }) },
    { id: 'request.missing-trace', model: 'RequestMeta', valid: false,
      payload: '{"requestId":"r"}' },
    { id: 'request.null-locale', model: 'RequestMeta', valid: false,
      payload: '{"requestId":"r","traceId":"t","locale":null}' },
    { id: 'request.unknown-field', model: 'RequestMeta', valid: false,
      payload: '{"requestId":"r","traceId":"t","userId":"not-authorized"}' },
    { id: 'request.prototype-key', model: 'RequestMeta', valid: false,
      payload: '{"requestId":"r","traceId":"t","__proto__":{}}' },

    { id: 'page.minimum', model: 'PageQuery', valid: true, payload: '{"limit":1}' },
    { id: 'page.maximum', model: 'PageQuery', valid: true,
      payload: '{"limit":100,"cursor":"c"}' },
    { id: 'page.integral-decimal', model: 'PageQuery', valid: true, payload: '{"limit":18.0}' },
    { id: 'page.integral-exponent', model: 'PageQuery', valid: true, payload: '{"limit":1.8e1}' },
    { id: 'page.fraction', model: 'PageQuery', valid: false, payload: '{"limit":18.5}' },
    { id: 'page.coercible-string', model: 'PageQuery', valid: false, payload: '{"limit":"18"}' },
    { id: 'page.missing-limit-no-default-insertion', model: 'PageQuery', valid: false, payload: '{}' },
    { id: 'page.null-cursor', model: 'PageQuery', valid: false,
      payload: '{"limit":18,"cursor":null}' },
    { id: 'page.empty-cursor', model: 'PageQuery', valid: false,
      payload: '{"limit":18,"cursor":""}' },
    { id: 'page.cursor-max-codepoints', model: 'PageQuery', valid: true,
      payload: JSON.stringify({ limit: 18, cursor: emoji(512) }) },
    { id: 'page.cursor-over-codepoints', model: 'PageQuery', valid: false,
      payload: JSON.stringify({ limit: 18, cursor: emoji(513) }) },
    { id: 'page.unknown-field', model: 'PageQuery', valid: false,
      payload: '{"limit":18,"offset":0}' },

    { id: 'problem.minimum', model: 'ProblemDetails', valid: true,
      payload: '{"type":"error","title":"Error","status":400,"requestId":"r"}' },
    { id: 'problem.maximum', model: 'ProblemDetails', valid: true,
      payload: '{"type":"error","title":"Error","status":599,"requestId":"r","detail":""}' },
    { id: 'problem.status-too-small', model: 'ProblemDetails', valid: false,
      payload: '{"type":"error","title":"Error","status":399,"requestId":"r"}' },
    { id: 'problem.status-too-large', model: 'ProblemDetails', valid: false,
      payload: '{"type":"error","title":"Error","status":600,"requestId":"r"}' },
    { id: 'problem.integral-decimal-status', model: 'ProblemDetails', valid: true,
      payload: '{"type":"error","title":"Error","status":500.0,"requestId":"r"}' },
    { id: 'problem.null-detail', model: 'ProblemDetails', valid: false,
      payload: '{"type":"error","title":"Error","status":500,"requestId":"r","detail":null}' },
    { id: 'problem.missing-detail', model: 'ProblemDetails', valid: true,
      payload: '{"type":"error","title":"Error","status":500,"requestId":"r"}' },
    { id: 'problem.title-max-codepoints', model: 'ProblemDetails', valid: true,
      payload: JSON.stringify({ type: 'error', title: emoji(256), status: 500, requestId: 'r' }) },
    { id: 'problem.title-over-codepoints', model: 'ProblemDetails', valid: false,
      payload: JSON.stringify({ type: 'error', title: emoji(257), status: 500, requestId: 'r' }) },
    { id: 'problem.unknown-field', model: 'ProblemDetails', valid: false,
      payload: '{"type":"error","title":"Error","status":500,"requestId":"r","debug":true}' },

    { id: 'union.request', model: 'PublicValidationContract', valid: true,
      payload: '{"requestId":"r","traceId":"t"}' },
    { id: 'union.page-integral-decimal', model: 'PublicValidationContract', valid: true,
      payload: '{"limit":18.0}' },
    { id: 'union.problem', model: 'PublicValidationContract', valid: true,
      payload: '{"type":"error","title":"Error","status":500,"requestId":"r"}' },
    { id: 'union.mixed', model: 'PublicValidationContract', valid: false,
      payload: '{"requestId":"r","traceId":"t","limit":18}' },
    { id: 'union.empty', model: 'PublicValidationContract', valid: false, payload: '{}' },
    { id: 'union.null', model: 'PublicValidationContract', valid: false, payload: 'null' },
    { id: 'union.array', model: 'PublicValidationContract', valid: false, payload: '[]' },
  ]);
}
